language: python

# Version to Test Against
python:
  - "2.6"
  - "2.7"

# Install Dependencies
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libpam0g-dev
    - sudo apt-get install -y libcurl4-openssl-dev
    - sudo apt-get install -y glib2.0
    - sudo apt-get install -y libgtest-dev gcc g++

# Old debian systems:
#    - sudo apt-get install -y libpam0g-dev
#    - sudo apt-get install -y libreadline5-dev

# Newer debian systems:
#    - sudo apt-get install -y libreadline-gplv2-dev

# For gnutils SSL instead of openssl
#    - sudo apt-get install libcurl4-gnutls-dev

install:
    - pip install nose flask coveralls PyYAML PyJWT

# Run Tests
script:
    - 'export PYTHONPATH="${PYTHONPATH}:./pivportal/lib"'
    - "coverage run --source=pivportal $(which nosetests) -w pivportal/test/"
    - "cd pam_pivportal/ && make clean && make && make test"

after_success:
    - coveralls