language: python

# Version to Test Against
python:
  - "2.6"
  - "2.7"

# Install Dependencies
install:
    - pip install nose
    - apt-get install pam-devel libcurl-devel

# Run Tests
script:
    - 'export PYTHONPATH="${PYTHONPATH}:./pivportal/lib"'
    - "coverage run --source=pivportal $(which nosetests) -w pivportal/test/"
    - "cd pam_pivportal/ && make clean && make && make test"

after_success:
    - coveralls