language: python

# Version to Test Against
python:
  - "2.6"
  - "2.7"

# Install Dependencies
before_install:
    - sudo apt-get -qq update
#    - sudo apt-get install -y pam-devel libcurl-devel

install:
    - pip install nose

# Run Tests
script:
    - 'export PYTHONPATH="${PYTHONPATH}:./pivportal/lib"'
    - "coverage run --source=pivportal $(which nosetests) -w pivportal/test/"
    - "cd pam_pivportal/ && make clean && make && make test"

after_success:
    - coveralls